.PHONY: all
all: dmpzrpg.com zde17.com zdr.com zdr3.com

dmpzrpg.com: dmpzrpg.mac
	tnylpo zsm4 =dmpzrpg
	tnylpo link dmpzrpg

zde17.com: zde17.mac
	tnylpo zsm4 =zde17
	tnylpo link zde17

zdr.com: zdr.asm
	tnylpo mac zdr
	tnylpo load zdr

zdr3.com: zdr3.asm
	tnylpo mac zdr3
	tnylpo load zdr3
