.PHONY: all
all: dumppara.com zde17.com zdr.com zdr3.com

dumppara.com: dumppara.mac
	tnylpo zsm4 =dumppara
	tnylpo link dumppara

zde17.com: zde17.mac
	tnylpo zsm4 =zde17
	tnylpo link zde17

zdr.com: zdr.asm
	tnylpo mac zdr
	tnylpo load zdr

zdr3.com: zdr3.asm
	tnylpo mac zdr3
	tnylpo load zdr3
