#!/bin/sh

# PORT=/dev/ttyUSB0
# use unique device id
PORT=/dev/z80-mbc2

SCREEN_SIZE=120x40
FONT_SIZE=12


# connect to Z80-MBC2 board via serial interface
#
#   open a xterm with $SCREEN_SIZE, orange on black
#   mono font, size $FONT_SIZE
#   translate
#     VT100 cursor keys to CP/M cursor keys
#     UP -> ^E; DOWN -> ^X; LEFT -> ^S; RIGHT -> ^D
#     PageUp -> ^R; PageDown -> ^C
#     Home -> ^QS; End -> ^QD
#     Ctrl PageUp -> ^QR; Ctrl PageDown -> ^QC
#     Ctrl Home -> ^QE; Ctrl End -> ^QX
#     Insert -> ^Q
#     Delete -> ^G
#     BackSpace -> ^H
#   execute picocom in this terminal
#     open $PORT
#     115200 bps
#     use xmodem protocol for send "sx" and receive "rx"

xterm \
    -fa LiberationMono -fs $FONT_SIZE \
    -g $SCREEN_SIZE -fg orange -bg black \
    -title "Z80MBC2" \
    -xrm \
        "xterm*iconHint: $HOME/.local/share/icons/Z80MBC2.xpm" \
    -xrm \
        'xterm*VT100.translations: #override \n\
        Ctrl <Key>Prior:                string(0x11) string(0x12) \n\
        Ctrl <Key>Next:                 string(0x11) string(0x03) \n\
        Ctrl <Key>Home:                 string(0x11) string(0x05) \n\
        Ctrl <Key>End:                  string(0x11) string(0x18) \n\
        Ctrl ~@Num_Lock <Key>KP_Prior:  string(0x11) string(0x12) \n\
        Ctrl ~@Num_Lock <Key>KP_Next:   string(0x11) string(0x03) \n\
        Ctrl ~@Num_Lock <Key>KP_Home:   string(0x11) string(0x05) \n\
        Ctrl ~@Num_Lock <Key>KP_End:    string(0x11) string(0x18) \n\
        <Key>Up:                        string(0x05) \n\
        <Key>Down:                      string(0x18) \n\
        <Key>Right:                     string(0x04) \n\
        <Key>Left:                      string(0x13) \n\
        <Key>Prior:                     string(0x12) \n\
        <Key>Next:                      string(0x03) \n\
        <Key>Home:                      string(0x11) string(0x13) \n\
        <Key>End:                       string(0x11) string(0x04) \n\
        <Key>BackSpace:                 string(0x08) \n\
        <Key>Insert:                    string(0x16) \n\
        <Key>Delete:                    string(0x07) \n\
        ~@Num_Lock <Key>KP_Up:          string(0x05) \n\
        ~@Num_Lock <Key>KP_Down:        string(0x18) \n\
        ~@Num_Lock <Key>KP_Right:       string(0x04) \n\
        ~@Num_Lock <Key>KP_Left:        string(0x13) \n\
        ~@Num_Lock <Key>KP_Prior:       string(0x12) \n\
        ~@Num_Lock <Key>KP_Next:        string(0x03) \n\
        ~@Num_Lock <Key>KP_Home:        string(0x11) string(0x13) \n\
        ~@Num_Lock <Key>KP_End:         string(0x11) string(0x04) \n\
        ~@Num_Lock <Key>KP_Insert:      string(0x16) \n\
        ~@Num_Lock <Key>KP_Delete:      string(0x07) \n\
        <Key>KP_Separator:              string(0x2E)' \
    -e  "picocom --send-cmd 'sx -b' --receive-cmd 'rx -b' \
                 -b 115200 $PORT"
